version: "3"
services:
  db:
    image: postgres:latest
    container_name: twtContainer
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER_ID}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - ./data1/db:/var/lib/postgresql/data